# Generated by Django 4.2.7 on 2026-04-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_recipie_5c719b_idx',
            old_name='api_notific_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_recipie_28b188_idx',
            old_name='api_notific_recipie_idx2',
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'following'], name='api_follow_followe_1822a8_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='api_follow_followi_d507a8_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['user', '-created_at'], name='api_reel_user_id_4de8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['-created_at'], name='api_reel_created_210b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'reel'], name='api_vote_user_id_c187df_idx'),
        ),
    ]
