# Generated by Django 4.2.7 on 2026-04-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_campaign_system_extended'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaderboard',
            new_name='api_leaderb_campaig_bd7cd0_idx',
            old_name='api_leaderb_campaig_idx',
        ),
        migrations.RenameIndex(
            model_name='leaderboardentry',
            new_name='api_leaderb_leaderb_87ff27_idx',
            old_name='api_leaderb_leaderb_idx',
        ),
        migrations.RenameIndex(
            model_name='postscore',
            new_name='api_postsco_campaig_a241e1_idx',
            old_name='api_postscor_campaig_idx',
        ),
        migrations.RenameIndex(
            model_name='postscore',
            new_name='api_postsco_user_id_17e6db_idx',
            old_name='api_postscor_user_ca_idx',
        ),
        migrations.RenameIndex(
            model_name='reel',
            new_name='api_reel_campaig_63d5c2_idx',
            old_name='api_reel_campaig_idx',
        ),
        migrations.RenameIndex(
            model_name='reel',
            new_name='api_reel_is_camp_25262a_idx',
            old_name='api_reel_is_camp_idx',
        ),
        migrations.RenameIndex(
            model_name='usercampaignstats',
            new_name='api_usercam_campaig_5bb83d_idx',
            old_name='api_usercam_campaig_idx',
        ),
        migrations.AddField(
            model_name='campaigntheme',
            name='hashtags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
