# Generated by Django 4.2.7 on 2026-04-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_clear_broken_cloudinary_404s'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('daily', 'Daily Campaign'), ('weekly', 'Weekly Campaign'), ('monthly', 'Monthly Campaign'), ('grand', 'Grand Campaign')], default='grand', help_text='Determines rules and scoring logic', max_length=20),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_random_percentage',
            field=models.IntegerField(default=30, help_text='Percentage of winners from random participants (Daily)'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_top_scorer_percentage',
            field=models.IntegerField(default=70, help_text='Percentage of winners from top scorers (Daily)'),
        ),
        migrations.AddField(
            model_name='usercampaignstats',
            name='has_won_current_cycle',
            field=models.BooleanField(default=False, help_text='True if user has won in the current active period (week/month)'),
        ),
        migrations.AddField(
            model_name='usercampaignstats',
            name='last_win_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
