# Generated by Django 4.2.7 on 2026-04-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_campaign_campaign_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='entry_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for submitting entries', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='voting_end',
            field=models.DateTimeField(blank=True, help_text='When voting ends', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='voting_start',
            field=models.DateTimeField(blank=True, help_text='When voting begins', null=True),
        ),
    ]
