# Generated by Django 4.2.7 on 2026-04-06 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_make_campaign_dates_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_coin_gift_weight',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points per coin gift received', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_comments_weight',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points per comment (Daily)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_likes_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points per like (Daily)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_login_bonus_weight',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Points for daily login bonus', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_post_points',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Points for posting that day', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_shares_weight',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Points per share (Daily)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_spin_reward_weight',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Points for daily spin reward', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_win_cooldown_days',
            field=models.IntegerField(default=7, help_text='Days before user can win again (Daily)'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_judge_creativity_max',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Max creativity points from judges', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_judge_impact_max',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Max impact points from judges', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_judge_quality_max',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Max quality points from judges', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_judge_theme_max',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Max theme relevance from judges', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_judging_weight',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='Weight for judge/admin scoring (0.0-1.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_max_votes_per_user',
            field=models.IntegerField(default=3, help_text='Max finalists a user can vote for'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_qualification_comments_weight',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points per comment (Qualification)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_qualification_likes_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points per like (Qualification)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_qualification_percentage',
            field=models.IntegerField(default=20, help_text='Top percentage that qualifies for finals'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_qualification_shares_weight',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Points per share (Qualification)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_vote_value',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Points per vote received', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_voting_weight',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='Weight for public voting (0.0-1.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_coin_gift_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points per coin gift (Monthly)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_comments_weight',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points per comment (Monthly)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_consistency_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for consistent posting', max_digits=3),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_high_engagement_bonus',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Bonus for high engagement posts', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_high_engagement_threshold',
            field=models.IntegerField(default=100, help_text='Likes threshold for high engagement'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_likes_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points per like (Monthly)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_shares_weight',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Points per share (Monthly)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_spin_reward_weight',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points for spin reward (Monthly)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_streak_14day_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for 14-day streak', max_digits=3),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_streak_21day_multiplier',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Multiplier for 21-day streak', max_digits=3),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_streak_7day_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.2, help_text='Multiplier for 7-day streak', max_digits=3),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_weekly_winner_bonus',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Bonus points for weekly campaign winners', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_coin_gift_weight',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Points per coin gift (Weekly)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_comments_weight',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points per comment (Weekly)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_consistency_boost',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Points per day participated', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_decay_max_days',
            field=models.IntegerField(default=3, help_text='Max days for decay calculation'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_decay_per_missed_day',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Points deducted per missed day', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_likes_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points per like (Weekly)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_shares_weight',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Points per share (Weekly)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_spin_reward_weight',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Points for spin reward (Weekly)', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_streak_3day_bonus',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Bonus for 3-day streak', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_streak_5day_bonus',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Bonus for 5-day streak', max_digits=5),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_streak_7day_bonus',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Bonus for 7-day streak (full week)', max_digits=5),
        ),
        migrations.CreateModel(
            name='PublicVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_votes', to='api.campaign')),
                ('finalist', models.ForeignKey(help_text='User being voted for', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_votes_received', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'finalist'], name='api_publicv_campaig_e75609_idx'), models.Index(fields=['campaign', 'voter'], name='api_publicv_campaig_5c0128_idx')],
                'unique_together': {('campaign', 'voter', 'finalist')},
            },
        ),
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creativity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('theme_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('impact_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('judge_comments', models.TextField(blank=True, help_text='Judge feedback/comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scores', to='api.campaign')),
                ('judge', models.ForeignKey(help_text='Judge who gave the score', on_delete=django.db.models.deletion.CASCADE, related_name='scores_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User being judged (the finalist)', on_delete=django.db.models.deletion.CASCADE, related_name='judge_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'user', 'judge')},
            },
        ),
        migrations.CreateModel(
            name='GrandFinalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qualification_rank', models.IntegerField()),
                ('judge_score_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vote_count', models.IntegerField(default=0)),
                ('vote_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_finalist', models.BooleanField(default=True)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalists', to='api.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_finals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['qualification_rank'],
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GamificationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('spin_reward', 'Daily Spin Reward'), ('coin_gift_received', 'Coin Gift Received'), ('coin_gift_sent', 'Coin Gift Sent'), ('login_bonus', 'Daily Login Bonus'), ('streak_bonus', 'Streak Bonus'), ('referral_bonus', 'Referral Bonus')], max_length=30)),
                ('points_value', models.DecimalField(decimal_places=2, default=0, help_text='Points earned for this activity', max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (e.g., spin result, gift sender)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_date', models.DateField(help_text='The date this activity counts for')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamification_activities', to='api.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'campaign', 'activity_date'], name='api_gamific_user_id_21a08c_idx'), models.Index(fields=['user', 'activity_type', 'activity_date'], name='api_gamific_user_id_adf056_idx')],
            },
        ),
    ]
