# Generated by Django 4.2.7 on 2026-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_flexible_scoring_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=0, help_text='User coin balance'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coins_earned_total',
            field=models.IntegerField(default=0, help_text='Total coins earned lifetime'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coins_spent_total',
            field=models.IntegerField(default=0, help_text='Total coins spent lifetime'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gifts_received_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gifts_received_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gifts_sent_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gifts_sent_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_gift_reset',
            field=models.DateField(blank=True, help_text='Last daily gift counter reset', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_spin_date',
            field=models.DateField(blank=True, help_text='Last daily spin date', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_streak',
            field=models.IntegerField(default=0, help_text='Consecutive login days'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longest_login_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spins_total',
            field=models.IntegerField(default=0, help_text='Total spins done'),
        ),
    ]
