# Generated by Django 4.2.7 on 2026-04-08 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_add_notinterested'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., "Season 1 Campaign"', max_length=200)),
                ('description', models.TextField(help_text='Overall description of the season')),
                ('image', models.ImageField(blank=True, null=True, upload_to='master_campaigns/')),
                ('start_date', models.DateTimeField(help_text='When the master campaign starts')),
                ('end_date', models.DateTimeField(help_text='When the master campaign ends')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('auto_generate_daily', models.BooleanField(default=True, help_text='Automatically generate daily campaigns')),
                ('auto_generate_weekly', models.BooleanField(default=True, help_text='Automatically generate weekly campaigns')),
                ('auto_generate_monthly', models.BooleanField(default=True, help_text='Automatically generate monthly campaigns')),
                ('auto_generate_grand', models.BooleanField(default=True, help_text='Automatically generate grand campaign')),
                ('min_followers', models.IntegerField(default=0, help_text='Minimum followers required to join')),
                ('min_level', models.IntegerField(default=1, help_text='Minimum user level required')),
                ('required_hashtags', models.CharField(blank=True, help_text='Comma-separated hashtags for all campaigns', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_participants', models.IntegerField(default=0)),
                ('total_daily_campaigns', models.IntegerField(default=0)),
                ('total_weekly_campaigns', models.IntegerField(default=0)),
                ('total_monthly_campaigns', models.IntegerField(default=0)),
                ('total_grand_campaigns', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterCampaignParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_daily_wins', models.IntegerField(default=0)),
                ('total_weekly_wins', models.IntegerField(default=0)),
                ('total_monthly_wins', models.IntegerField(default=0)),
                ('total_grand_wins', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
        migrations.RenameIndex(
            model_name='notinterested',
            new_name='api_notinte_user_id_2cb069_idx',
            old_name='api_notinte_user_id_7f6b3b_idx',
        ),
        migrations.RenameIndex(
            model_name='notinterested',
            new_name='api_notinte_user_id_1ce384_idx',
            old_name='api_notinte_user_id_e8f9c2_idx',
        ),
        migrations.AddField(
            model_name='mastercampaignparticipant',
            name='master_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.mastercampaign'),
        ),
        migrations.AddField(
            model_name='mastercampaignparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_campaign_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mastercampaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_master_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='master_campaign',
            field=models.ForeignKey(blank=True, help_text='Master Campaign this belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_campaigns', to='api.mastercampaign'),
        ),
        migrations.AlterUniqueTogether(
            name='mastercampaignparticipant',
            unique_together={('master_campaign', 'user')},
        ),
    ]
