# Generated by Django 4.2.7 on 2026-04-12 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0030_add_master_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('reel', 'Reel'), ('comment', 'Comment'), ('user', 'User')], default='reel', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('harassment', 'Harassment'), ('copyright', 'Copyright Violation'), ('scam', 'Scam/Fraud'), ('hate_speech', 'Hate Speech'), ('self_harm', 'Self Harm'), ('violence', 'Violence'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('warning', 'Warning Issued'), ('content_removed', 'Content Removed'), ('shadowban', 'Shadow Banned'), ('temp_ban', 'Temporary Ban'), ('permanent_ban', 'Permanent Ban'), ('no_action', 'No Action Taken')], max_length=30)),
                ('reason_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='api.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
