# Generated by Django 4.2.7 on 2026-04-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_overlay_text_to_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercampaign',
            name='daily_campaign_count',
            field=models.IntegerField(default=0, help_text='Number of daily campaigns (0 = all days in range)'),
        ),
        migrations.AddField(
            model_name='mastercampaign',
            name='grand_campaign_count',
            field=models.IntegerField(default=1, help_text='Number of grand campaigns (usually 1)'),
        ),
        migrations.AddField(
            model_name='mastercampaign',
            name='monthly_campaign_count',
            field=models.IntegerField(default=0, help_text='Number of monthly campaigns (0 = all months in range)'),
        ),
        migrations.AddField(
            model_name='mastercampaign',
            name='weekly_campaign_count',
            field=models.IntegerField(default=0, help_text='Number of weekly campaigns (0 = all weeks in range)'),
        ),
    ]
