# Generated by Django 4.2.7 on 2026-04-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_legaldocument_userlegalacceptance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='font_family_caption',
            field=models.CharField(default='Inter', help_text='Font for captions and descriptions', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='font_family_primary',
            field=models.CharField(default='Inter', help_text='Primary font for headings and UI', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='font_family_secondary',
            field=models.CharField(default='Inter', help_text='Secondary font for body text', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='font_family_username',
            field=models.CharField(default='Inter', help_text='Font for usernames', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='font_size_base',
            field=models.IntegerField(default=16, help_text='Base font size in pixels'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='font_weight_body',
            field=models.CharField(default='400', help_text='Font weight for body text', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='font_weight_headings',
            field=models.CharField(default='700', help_text='Font weight for headings', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='letter_spacing',
            field=models.CharField(default='normal', help_text='Letter spacing (e.g., normal, 0.5px, -0.02em)', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='line_height',
            field=models.CharField(default='1.5', help_text='Line height multiplier', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='primary_color',
            field=models.CharField(default='#8B5CF6', help_text='Primary brand color', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='secondary_color',
            field=models.CharField(default='#F97316', help_text='Secondary/accent color', max_length=20),
        ),
    ]
