# Generated by Django 4.2 on 2026-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_platformsettings_font_family_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
