# Generated by Django 4.2.7 on 2026-04-20 11:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_message_media'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='api_convers_last_me_eb2fc0_idx',
            old_name='api_convers_last_me_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_convers_ece45b_idx',
            old_name='api_message_convers_idx',
        ),
        migrations.RenameIndex(
            model_name='messageread',
            new_name='api_message_user_id_f38d8d_idx',
            old_name='api_msgread_user_co_idx',
        ),
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\hp\\Downloads\\Telegram Desktop\\postwork\\selfi_star\\backend\\media'), upload_to='messages/%Y/%m/'),
        ),
    ]
