# Generated by Django 4.2.7 on 2026-04-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_perf_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='api_comment_reel_id_36dd9e_idx',
            old_name='api_comment_reel_cr_idx',
        ),
        migrations.AddField(
            model_name='gifttocreator',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
