# Generated by Django 4.2.7 on 2026-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rename_api_comment_reel_cr_idx_api_comment_reel_id_36dd9e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('gift', 'Gift')], max_length=20),
        ),
    ]
