# Generated by Django 4.2 on 2026-04-22 08:31

import django.core.files.storage
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='glass_effect_enabled',
            field=models.BooleanField(default=False, help_text='Enable glass/crystal UI effect across the platform'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\hp\\Desktop\\selfi_starrr\\postworq\\selfi_star\\backend\\media'), upload_to='messages/%Y/%m/'),
        ),
    ]
