# Generated by Django 4.2.7 on 2026-04-24 08:51

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0045_platformsettings_glass_effect_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='Gift icon/image', upload_to='gifts/')),
                ('animated_image', models.ImageField(blank=True, help_text='Animated version of the gift', null=True, upload_to='gifts/animated/')),
                ('coin_value', models.IntegerField(default=1, help_text='Cost in coins to send this gift')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('category', models.CharField(choices=[('flowers', 'Flowers'), ('hearts', 'Hearts'), ('gems', 'Gems'), ('special', 'Special'), ('animals', 'Animals'), ('vehicles', 'Vehicles')], default='special', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this gift is available for sending')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order in gift selector')),
                ('xp_reward', models.IntegerField(default=0, help_text='XP reward for sender')),
                ('animation_type', models.CharField(blank=True, help_text='Animation type (e.g., particle, bounce, pulse)', max_length=50)),
                ('animation_duration', models.FloatField(default=1.0, help_text='Animation duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'coin_value', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\hp\\Downloads\\Telegram Desktop\\postwork\\selfi_star\\backend\\media'), upload_to='messages/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='UserGiftStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gifts_sent', models.IntegerField(default=0)),
                ('total_coins_sent', models.IntegerField(default=0)),
                ('unique_recipients', models.IntegerField(default=0, help_text='Number of different users they gifted')),
                ('total_gifts_received', models.IntegerField(default=0)),
                ('total_coins_received', models.IntegerField(default=0)),
                ('unique_senders', models.IntegerField(default=0, help_text='Number of different users who gifted them')),
                ('highest_combo', models.IntegerField(default=0, help_text='Highest combo achieved')),
                ('total_combos', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_gift_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_receivers', to='api.gift')),
                ('favorite_gift_sent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_senders', to='api.gift')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Gift Stats',
            },
        ),
        migrations.CreateModel(
            name='GiftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Number of gifts sent (combo)')),
                ('total_coins', models.IntegerField(help_text='Total coins spent')),
                ('is_combo', models.BooleanField(default=False, help_text='Whether this was part of a combo')),
                ('combo_multiplier', models.FloatField(default=1.0, help_text='Multiplier for combo gifts')),
                ('message', models.TextField(blank=True, help_text='Optional message with the gift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.gift')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
                ('reel', models.ForeignKey(blank=True, help_text='The reel this gift was sent on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_received', to='api.reel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_count', models.IntegerField(default=1, help_text='Number of gifts in combo')),
                ('total_coins', models.IntegerField(help_text='Total coins spent in combo')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_gift_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether combo can still be added to')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gift')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_combos', to='api.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_combos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['is_active', 'sort_order'], name='api_gift_is_acti_a13fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['category', 'is_active'], name='api_gift_categor_3d231a_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['rarity'], name='api_gift_rarity_032533_idx'),
        ),
        migrations.AddIndex(
            model_name='gifttransaction',
            index=models.Index(fields=['sender', '-created_at'], name='api_gifttra_sender__3e35eb_idx'),
        ),
        migrations.AddIndex(
            model_name='gifttransaction',
            index=models.Index(fields=['recipient', '-created_at'], name='api_gifttra_recipie_3a91fd_idx'),
        ),
        migrations.AddIndex(
            model_name='gifttransaction',
            index=models.Index(fields=['gift', '-created_at'], name='api_gifttra_gift_id_22da41_idx'),
        ),
        migrations.AddIndex(
            model_name='gifttransaction',
            index=models.Index(fields=['reel', '-created_at'], name='api_gifttra_reel_id_77b8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcombo',
            index=models.Index(fields=['user', '-started_at'], name='api_giftcom_user_id_eba846_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcombo',
            index=models.Index(fields=['reel', '-started_at'], name='api_giftcom_reel_id_0f9007_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcombo',
            index=models.Index(fields=['is_active'], name='api_giftcom_is_acti_3c20be_idx'),
        ),
    ]
