# Generated by Django 4.2.7 on 2026-04-24 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0046_gift_alter_message_media_usergiftstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttocreator',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_gifts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gifttocreator',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_gifts_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
