# Generated by Django 4.2.7 on 2026-04-24 09:30

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_gifttocreator_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='glass_effect_enabled',
        ),
    ]
