# Generated by Django 4.2.7 on 2026-04-27 06:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0048_remove_platformsettings_glass_effect_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='icon_color',
            field=models.CharField(blank=True, default='#FFD700', help_text='Hex color for the lucide icon (e.g., #FF0080 for hearts)', max_length=20),
        ),
        migrations.AddField(
            model_name='gift',
            name='icon_name',
            field=models.CharField(blank=True, default='Gift', help_text='lucide-react icon name (e.g., Heart, Star, Crown, Diamond)', max_length=50),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='earned_balance',
            field=models.PositiveIntegerField(default=0, help_text='From rewards. Cannot be gifted.'),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='purchased_balance',
            field=models.PositiveIntegerField(default=0, help_text='Bought via Telebirr. Full use.'),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='total_purchased',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime coins bought'),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='total_withdrawn',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime coins withdrawn to Birr'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase (Telebirr)'), ('welcome_bonus', 'Welcome Bonus'), ('daily_login', 'Daily Login Bonus'), ('spin_reward', 'Daily Spin Reward'), ('post_bonus', 'Daily Post Bonus'), ('campaign_join', 'Campaign Join Reward'), ('campaign_winner', 'Campaign Winner Reward'), ('like_received', 'Like Received'), ('comment_reward', 'Quality Comment Reward'), ('referral', 'Referral Bonus'), ('profile_complete', 'Profile Completion'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received'), ('boost', 'Post Boost'), ('extra_entry', 'Extra Entry'), ('reward', 'Generic Reward'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal to Birr'), ('admin_adjustment', 'Admin Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional uploaded icon/image (overrides icon_name if set)', null=True, upload_to='gifts/'),
        ),
        migrations.CreateModel(
            name='WalletConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_bonus', models.PositiveIntegerField(default=100, help_text='Coins given to new users on signup')),
                ('daily_login_day1', models.PositiveIntegerField(default=5)),
                ('daily_login_day2', models.PositiveIntegerField(default=10)),
                ('daily_login_day3', models.PositiveIntegerField(default=15)),
                ('daily_login_day4', models.PositiveIntegerField(default=20)),
                ('daily_login_day5', models.PositiveIntegerField(default=25)),
                ('daily_login_day6', models.PositiveIntegerField(default=30)),
                ('daily_login_day7', models.PositiveIntegerField(default=50)),
                ('daily_post_bonus', models.PositiveIntegerField(default=20, help_text='Coins for first post of the day')),
                ('campaign_join_reward', models.PositiveIntegerField(default=30, help_text='Coins for joining a campaign')),
                ('receive_like_reward', models.PositiveIntegerField(default=1, help_text='Coins per like received')),
                ('receive_like_daily_cap', models.PositiveIntegerField(default=100, help_text='Max coins/day from likes')),
                ('quality_comment_reward', models.PositiveIntegerField(default=2, help_text='Coins per long comment')),
                ('quality_comment_daily_cap', models.PositiveIntegerField(default=20)),
                ('profile_complete_reward', models.PositiveIntegerField(default=50, help_text='One-time reward')),
                ('referral_reward', models.PositiveIntegerField(default=100, help_text='Coins per friend signup')),
                ('campaign_winner_reward', models.PositiveIntegerField(default=500, help_text='Bonus for winning a campaign')),
                ('cost_post_create', models.PositiveIntegerField(default=0, help_text='Cost to create a post (0 = free)')),
                ('cost_like', models.PositiveIntegerField(default=0)),
                ('cost_comment', models.PositiveIntegerField(default=0)),
                ('cost_join_campaign', models.PositiveIntegerField(default=50)),
                ('cost_extra_campaign_entry', models.PositiveIntegerField(default=100)),
                ('cost_boost_2hr', models.PositiveIntegerField(default=200)),
                ('cost_boost_24hr', models.PositiveIntegerField(default=800)),
                ('min_balance_to_post', models.PositiveIntegerField(default=0)),
                ('min_balance_to_join_campaign', models.PositiveIntegerField(default=50)),
                ('withdrawal_enabled', models.BooleanField(default=True, help_text='Allow users to withdraw coins to Birr')),
                ('withdrawal_min_coins', models.PositiveIntegerField(default=1000, help_text='Minimum coins required to withdraw')),
                ('withdrawal_max_coins_per_request', models.PositiveIntegerField(default=100000)),
                ('coins_per_birr', models.PositiveIntegerField(default=100, help_text='How many coins = 1 ETB (e.g. 100 means 100 coins -> 1 ETB)')),
                ('withdrawal_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Service fee % on withdrawal', max_digits=5)),
                ('withdrawal_processing_days', models.PositiveIntegerField(default=3, help_text='Days to process withdrawal')),
                ('earned_coins_giftable', models.BooleanField(default=False, help_text='Can earned coins be sent as gifts?')),
                ('purchased_coins_giftable', models.BooleanField(default=True)),
                ('earned_coins_withdrawable', models.BooleanField(default=True, help_text='Can earned coins be withdrawn to Birr?')),
                ('purchased_coins_withdrawable', models.BooleanField(default=False, help_text='Should not allow purchased->Birr (money laundering)')),
                ('earned_coins_expire_days', models.PositiveIntegerField(default=0, help_text='0 = never expire')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Configuration',
                'verbose_name_plural': 'Wallet Configuration',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.PositiveIntegerField(help_text='Coins to convert')),
                ('gross_birr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_birr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_birr', models.DecimalField(decimal_places=2, help_text='Final amount sent to user', max_digits=12)),
                ('conversion_rate', models.PositiveIntegerField(help_text='Coins per Birr at time of request')),
                ('payout_method', models.CharField(choices=[('telebirr', 'Telebirr'), ('bank_transfer', 'Bank Transfer'), ('cbe_birr', 'CBE Birr'), ('mpesa', 'M-Pesa Ethiopia')], default='telebirr', max_length=20)),
                ('payout_account', models.CharField(help_text='Phone number or bank account', max_length=100)),
                ('payout_account_name', models.CharField(blank=True, help_text='Account holder name', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing Payout'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by User')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('payout_reference', models.CharField(blank=True, help_text='Telebirr/bank reference number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_withdra_user_id_4e3c7f_idx'), models.Index(fields=['status', '-created_at'], name='api_withdra_status_8c33b7_idx')],
            },
        ),
    ]
