# Generated by Django 4.2.7 on 2026-04-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_merge_0043_phone_otp_password_reset_0049_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_likes', to='api.commentreply'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0, help_text='User point balance (convertible to birr)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points_earned_total',
            field=models.IntegerField(default=0, help_text='Total points earned lifetime'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points_withdrawn_total',
            field=models.IntegerField(default=0, help_text='Total points withdrawn lifetime'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='coins_to_points_conversion',
            field=models.PositiveIntegerField(default=1, help_text='How many coins = 1 point (gift conversion)'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='points_per_birr',
            field=models.PositiveIntegerField(default=10, help_text='How many points = 1 ETB (withdrawal)'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='withdrawal_max_points_per_request',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='withdrawal_min_points',
            field=models.PositiveIntegerField(default=100, help_text='Minimum points required to withdraw'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='point_amount',
            field=models.PositiveIntegerField(default=0, help_text='Points to convert to birr'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='coin_amount',
            field=models.PositiveIntegerField(default=0, help_text='Coins to convert (legacy, use point_amount instead)'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='conversion_rate',
            field=models.PositiveIntegerField(help_text='Coins/Points per Birr at time of request'),
        ),
        migrations.AddIndex(
            model_name='campaignentry',
            index=models.Index(fields=['campaign', 'approved', 'disqualified'], name='entry_campaign_filter_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment'), name='unique_user_comment_like'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(condition=models.Q(('reply__isnull', False)), fields=('user', 'reply'), name='unique_user_reply_like'),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
