# Generated by Django 4.2.7 on 2026-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_passwordresettoken_user_delete_phoneotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletconfig',
            name='daily_winner_points',
            field=models.PositiveIntegerField(default=500, help_text='Points awarded to daily campaign winners'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='grand_finalist_points',
            field=models.PositiveIntegerField(default=5000, help_text='Points awarded to grand campaign finalists'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='grand_winner_points',
            field=models.PositiveIntegerField(default=50000, help_text='Points awarded to grand campaign winners'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='monthly_winner_points',
            field=models.PositiveIntegerField(default=10000, help_text='Points awarded to monthly campaign winners'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='weekly_winner_points',
            field=models.PositiveIntegerField(default=2000, help_text='Points awarded to weekly campaign winners'),
        ),
    ]
