# Generated by Django 4.2.7 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_adminrole_expiredsubscriptionaction_onevaswebhooklog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_used_free_trial',
            field=models.BooleanField(default=False, help_text='User has used their 1-day free trial'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='free_trial_days',
            field=models.IntegerField(default=0, help_text='Number of free trial days granted'),
        ),
    ]
