# Generated by Django 4.2.7 on 2026-04-30 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0058_alter_subscriptioncointransaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
