# Generated by Django 4.2.7 on 2026-04-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_subscriptionhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_source',
            field=models.CharField(choices=[('sms', 'SMS'), ('app', 'App')], default='app', max_length=20),
        ),
    ]
