# Generated by Django 4.2.7 on 2026-04-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_subscriptionplan_subscription_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='setup_otp',
            field=models.CharField(blank=True, help_text='OTP for account setup after SMS subscription', max_length=6, null=True),
        ),
    ]
