# Generated by Django 4.2.7 on 2026-05-13 11:32

from decimal import Decimal
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0069_supportrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnevasChargingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='User phone number for charging', max_length=20)),
                ('product_number', models.CharField(help_text='Onevas product number', max_length=50)),
                ('application_key', models.CharField(help_text='Onevas application key used', max_length=100)),
                ('amount_etb', models.DecimalField(decimal_places=2, help_text='Amount charged in ETB', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('insufficient_balance', 'Insufficient Balance'), ('timeout', 'Timeout')], default='pending', max_length=30)),
                ('transaction_id', models.CharField(blank=True, help_text='Onevas transaction ID', max_length=100, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('webhook_received', models.BooleanField(default=False)),
                ('webhook_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onevas Charging Transaction',
                'verbose_name_plural': 'Onevas Charging Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='mention',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='api_follow_followe_1822a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='api_follow_followi_d507a8_idx',
        ),
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='api_pushsub_user_id_2d7996_idx',
            old_name='api_pushsub_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='supportrequest',
            new_name='support_req_user_id_526c2d_idx',
            old_name='support_req_user_id_e1cd47_idx',
        ),
        migrations.RenameIndex(
            model_name='supportrequest',
            new_name='support_req_status_30a1dd_idx',
            old_name='support_req_status_5b3c4d_idx',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='api.commentreply'),
        ),
        migrations.AddField(
            model_name='mention',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='follows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='likes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='blurhash',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reel',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Coin Purchase'), ('welcome_bonus', 'Welcome Bonus'), ('daily_login', 'Daily Login Bonus'), ('spin_reward', 'Daily Spin Reward'), ('post_bonus', 'Daily Post Bonus'), ('campaign_join', 'Campaign Join Reward'), ('campaign_winner', 'Campaign Winner Reward'), ('like_received', 'Like Received'), ('comment_reward', 'Quality Comment Reward'), ('referral', 'Referral Bonus'), ('profile_complete', 'Profile Completion'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received'), ('boost', 'Post Boost'), ('extra_entry', 'Extra Entry'), ('reward', 'Generic Reward'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal to Birr'), ('admin_adjustment', 'Admin Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mention',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='mentioned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mention',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='api.commentreply'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\hp\\Downloads\\Telegram Desktop\\postwork\\flipstar\\backend\\media'), upload_to='messages/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='withdrawal_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Service fee % on withdrawal', max_digits=5),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='withdrawal_max_points_per_request',
            field=models.PositiveIntegerField(default=10000, help_text='Maximum points that can be withdrawn per request'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['mentioned_user', 'created_at'], name='api_mention_mention_9c561e_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['comment'], name='api_mention_comment_3d97da_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['reply'], name='api_mention_reply_i_4c754a_idx'),
        ),
        migrations.AddField(
            model_name='onevaschargingtransaction',
            name='subscription_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_transactions', to='api.subscriptiontier'),
        ),
        migrations.AddField(
            model_name='onevaschargingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='onevaschargingtransaction',
            index=models.Index(fields=['user', '-created_at'], name='api_onevasc_user_id_c4df58_idx'),
        ),
        migrations.AddIndex(
            model_name='onevaschargingtransaction',
            index=models.Index(fields=['status', '-created_at'], name='api_onevasc_status_8c399a_idx'),
        ),
        migrations.AddIndex(
            model_name='onevaschargingtransaction',
            index=models.Index(fields=['phone_number'], name='api_onevasc_phone_n_f96ffa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked')},
        ),
    ]
