# Generated by Django 4.2.7 on 2026-05-15 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0071_reel_shares_alter_subscriptionplan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='payment_method',
            field=models.CharField(choices=[('onevas', 'Onevas Airtime'), ('telebirr', 'Telebirr'), ('coins', 'Coins')], default='onevas', max_length=20),
        ),
        migrations.CreateModel(
            name='DirectDebitMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_msisdn', models.CharField(help_text='Payer phone number (MSISDN)', max_length=20)),
                ('payer_reference_number', models.CharField(help_text='Payer reference number for mandate', max_length=100)),
                ('payer_account_name', models.CharField(blank=True, help_text='Payer account name', max_length=64)),
                ('payee_identifier_type', models.IntegerField(choices=[(1, 'MSISDN'), (4, 'Shortcode'), (11, 'Organization Operator ID'), (14, 'SP Operator Username'), (53, 'Payer Reference Number')], default=4, help_text='Payee identifier type')),
                ('payee_identifier_value', models.CharField(help_text='Payee shortcode or ID', max_length=50)),
                ('payee_account_name', models.CharField(default='Flipstar', help_text='Payee account name', max_length=64)),
                ('mandate_id', models.CharField(blank=True, help_text='Telebirr mandate ID (max 18 bytes)', max_length=18, null=True)),
                ('status', models.CharField(choices=[('pending_created', 'Pending Creation'), ('pending_active', 'Pending Activation'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending_created', max_length=20)),
                ('frequency', models.CharField(choices=[('01', 'Once'), ('02', 'Daily'), ('03', 'Weekly'), ('04', 'Bi-weekly'), ('05', 'Monthly'), ('06', 'Quarterly'), ('07', 'Half-yearly'), ('08', 'Yearly')], help_text='Debit frequency', max_length=2)),
                ('first_payment_date', models.DateField(help_text='First payment date')),
                ('expiry_date', models.DateField(help_text='Mandate expiry date')),
                ('start_range_of_days', models.IntegerField(default=1, help_text='Start range of days for payment')),
                ('end_range_of_days', models.IntegerField(default=22, help_text='End range of days for payment')),
                ('agreed_tc', models.BooleanField(default=False, help_text='User agreed to terms and conditions')),
                ('originator_conversation_id', models.CharField(blank=True, help_text='Originator conversation ID', max_length=100)),
                ('conversation_id', models.CharField(blank=True, help_text='Telebirr conversation ID', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, help_text='Error message if mandate failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_plan', models.ForeignKey(blank=True, help_text='Linked subscription plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_debit_mandates', to='api.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_debit_mandates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direct Debit Mandate',
                'verbose_name_plural': 'Direct Debit Mandates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectDebitTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Debit amount', max_digits=10)),
                ('currency', models.CharField(default='ETB', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('telebirr_transaction_id', models.CharField(blank=True, help_text='Telebirr transaction ID', max_length=100)),
                ('originator_conversation_id', models.CharField(blank=True, help_text='Originator conversation ID', max_length=100)),
                ('conversation_id', models.CharField(blank=True, help_text='Telebirr conversation ID', max_length=100)),
                ('error_message', models.TextField(blank=True, help_text='Error message if transaction failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mandate', models.ForeignKey(help_text='Associated mandate', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.directdebitmandate')),
                ('subscription_payment', models.ForeignKey(blank=True, help_text='Associated subscription payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_debit_transactions', to='api.subscriptionpayment')),
            ],
            options={
                'verbose_name': 'Direct Debit Transaction',
                'verbose_name_plural': 'Direct Debit Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mandate', '-created_at'], name='api_directd_mandate_8434aa_idx'), models.Index(fields=['status', '-created_at'], name='api_directd_status_8be03a_idx'), models.Index(fields=['telebirr_transaction_id'], name='api_directd_telebir_322ae3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='directdebitmandate',
            index=models.Index(fields=['user', '-created_at'], name='api_directd_user_id_c08a08_idx'),
        ),
        migrations.AddIndex(
            model_name='directdebitmandate',
            index=models.Index(fields=['status', '-created_at'], name='api_directd_status_6d7312_idx'),
        ),
        migrations.AddIndex(
            model_name='directdebitmandate',
            index=models.Index(fields=['mandate_id'], name='api_directd_mandate_02071c_idx'),
        ),
        migrations.AddIndex(
            model_name='directdebitmandate',
            index=models.Index(fields=['payer_msisdn'], name='api_directd_payer_m_7edf8c_idx'),
        ),
    ]
