# Generated by Django 4.2.7 on 2026-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_add_payment_method_to_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletconfig',
            name='cost_boost_1hr',
            field=models.PositiveIntegerField(default=100, help_text='Cost to boost post for 1 hour'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_trending_1hr',
            field=models.PositiveIntegerField(default=150, help_text='Cost to make post trending for 1 hour'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_trending_24hr',
            field=models.PositiveIntegerField(default=1200, help_text='Cost to make post trending for 24 hours'),
        ),
    ]
