# Generated by Django 4.2.7 on 2026-05-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_walletconfig_cost_boost_1hr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletconfig',
            name='gift_max_points_per_transaction',
            field=models.PositiveIntegerField(default=5000, help_text='Maximum points per single gift'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='gift_max_points_to_recipient_per_day',
            field=models.PositiveIntegerField(default=5000, help_text='Max points to one recipient per day (Voting Cap)'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='gift_max_total_points_sent_per_day',
            field=models.PositiveIntegerField(default=10000, help_text='Max total points sent per user per day'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='gift_min_points_per_transaction',
            field=models.PositiveIntegerField(default=10, help_text='Minimum points per gift transaction'),
        ),
    ]
