# Generated by Django 4.2.7 on 2026-05-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_walletconfig_gift_max_points_per_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletconfig',
            name='withdrawal_min_points',
            field=models.PositiveIntegerField(default=1000, help_text='Minimum points required to withdraw'),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='withdrawal_max_points_per_request',
            field=models.PositiveIntegerField(default=50000, help_text='Maximum points that can be withdrawn per request'),
        ),
    ]
