# Generated by Django 4.2.7 on 2026-05-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_add_category_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebitmandate',
            name='payment_type',
            field=models.CharField(choices=[('recurring', 'Recurring Subscription'), ('one_off', 'One-Off Payment')], default='recurring', help_text='Payment type: recurring or one-off', max_length=20),
        ),
    ]
