# Generated by Django 4.2.7 on 2026-05-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_userprofile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletconfig',
            name='cost_boost_1hr_non_campaign',
            field=models.PositiveIntegerField(default=100, help_text='Cost to boost non-campaign post for 1 hour'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_boost_24hr_non_campaign',
            field=models.PositiveIntegerField(default=800),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_boost_2hr_non_campaign',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_comment_non_campaign',
            field=models.PositiveIntegerField(default=0, help_text='Coins charged when commenting on a non-campaign post (0 = free)'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_gift_non_campaign',
            field=models.PositiveIntegerField(default=0, help_text='Extra coins charged on top of gift value when gifting on a non-campaign post (0 = free)'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_like_non_campaign',
            field=models.PositiveIntegerField(default=0, help_text='Coins charged when liking a non-campaign post (0 = free)'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_post_create_non_campaign',
            field=models.PositiveIntegerField(default=0, help_text='Cost to create a non-campaign post (0 = free)'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_share_non_campaign',
            field=models.PositiveIntegerField(default=0, help_text='Coins charged when sharing a non-campaign post (0 = free)'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_trending_1hr_non_campaign',
            field=models.PositiveIntegerField(default=150, help_text='Cost to make non-campaign post trending for 1 hour'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_trending_24hr_non_campaign',
            field=models.PositiveIntegerField(default=1200, help_text='Cost to make non-campaign post trending for 24 hours'),
        ),
    ]
