# Generated by Django 4.2.7 on 2026-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_walletconfig_cost_boost_1hr_non_campaign_and_more'),
    ]

    operations = [
        # mentions field already exists, removed from this migration
    ]
