# Generated by Django 4.2.7 on 2026-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_notificationpreference_mentions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletconfig',
            name='cost_post_create_long_video',
            field=models.PositiveIntegerField(default=0, help_text='Additional coins for campaign videos > 60 seconds (0 = free)'),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='cost_post_create_long_video_non_campaign',
            field=models.PositiveIntegerField(default=0, help_text='Additional coins for non-campaign videos > 60 seconds (0 = free)'),
        ),
    ]
