# Generated by Django 4.2.7 on 2026-05-21 08:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0084_walletconfig_long_video_coin_costs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_hours', models.IntegerField(choices=[(1, '1 Hour'), (6, '6 Hours'), (12, '12 Hours'), (24, '24 Hours'), (72, '3 Days'), (168, '7 Days')])),
                ('coins_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coins_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('expected_impressions', models.IntegerField(help_text='Expected impressions based on cost')),
                ('impressions_served', models.IntegerField(default=0)),
                ('engagement_count', models.IntegerField(default=0, help_text='Total engagements (likes + comments + shares)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('exhausted', 'Budget Exhausted')], default='active', max_length=20)),
                ('target_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], help_text='Target audience gender', max_length=10, null=True)),
                ('target_age_min', models.IntegerField(blank=True, help_text='Minimum age', null=True)),
                ('target_age_max', models.IntegerField(blank=True, help_text='Maximum age', null=True)),
                ('target_location', models.CharField(blank=True, help_text='Target city/region', max_length=100)),
                ('hourly_budget', models.DecimalField(decimal_places=2, help_text='Coins per hour budget', max_digits=10)),
                ('last_pacing_check', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Base cost per hour in coins', max_digits=10)),
                ('discount_6hr', models.IntegerField(default=17, help_text='Discount % for 6-hour boost')),
                ('discount_12hr', models.IntegerField(default=33, help_text='Discount % for 12-hour boost')),
                ('discount_24hr', models.IntegerField(default=42, help_text='Discount % for 24-hour boost')),
                ('discount_3day', models.IntegerField(default=56, help_text='Discount % for 3-day boost')),
                ('discount_7day', models.IntegerField(default=71, help_text='Discount % for 7-day boost')),
                ('base_impression_rate', models.IntegerField(default=10, help_text='Base impressions per coin (1 coin = X impressions)')),
                ('platform_fee_percent', models.IntegerField(default=10, help_text='Platform fee percentage on top of boost cost')),
                ('pacing_tolerance', models.DecimalField(decimal_places=2, default=Decimal('1.20'), help_text='Allow 20% over-spend tolerance', max_digits=3)),
                ('min_duration_hours', models.IntegerField(default=1, help_text='Minimum boost duration in hours')),
                ('max_duration_hours', models.IntegerField(default=168, help_text='Maximum boost duration in hours (7 days)')),
                ('injection_ratio', models.IntegerField(default=4, help_text='1 boost per X organic posts')),
                ('frequency_cap_hours', models.IntegerField(default=12, help_text='Hours before same user can see same boost again')),
                ('max_daily_boosts_per_user', models.IntegerField(default=5, help_text='Max boosts per day per user')),
                ('max_active_boosts_per_post', models.IntegerField(default=3, help_text='Max concurrent boosts per post')),
                ('premium_targeting_surcharge', models.IntegerField(default=20, help_text='Additional % cost for premium targeting (age/gender/location)')),
                ('refund_threshold_percent', models.IntegerField(default=50, help_text='If less than X% of expected impressions served, refund X%')),
                ('cancellation_fee_percent', models.IntegerField(default=10, help_text='Cancellation fee percentage of remaining budget')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boost Configuration',
                'verbose_name_plural': 'Boost Configurations',
            },
        ),
        migrations.CreateModel(
            name='BoostEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('share', 'Share')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoostImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoostStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions_served', models.IntegerField(default=0)),
                ('engagements', models.IntegerField(default=0)),
                ('coins_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('hourly_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='mentions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='is_boosted',
            field=models.BooleanField(default=False, help_text='Whether this post is currently boosted'),
        ),
        migrations.AddField(
            model_name='reel',
            name='total_boost_engagements',
            field=models.IntegerField(default=0, help_text='Total engagements from all boost campaigns'),
        ),
        migrations.AddField(
            model_name='reel',
            name='total_boost_impressions',
            field=models.IntegerField(default=0, help_text='Total impressions from all boost campaigns'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['is_boosted', '-created_at'], name='api_reel_is_boos_bb977e_idx'),
        ),
        migrations.AddField(
            model_name='booststats',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='api.boostcampaign'),
        ),
        migrations.AddField(
            model_name='boostimpression',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='api.boostcampaign'),
        ),
        migrations.AddField(
            model_name='boostimpression',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_impressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boostengagement',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='api.boostcampaign'),
        ),
        migrations.AddField(
            model_name='boostengagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boostcampaign',
            name='reel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_campaigns', to='api.reel'),
        ),
        migrations.AddField(
            model_name='boostcampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reel',
            name='active_boost_campaign',
            field=models.ForeignKey(blank=True, help_text='Currently active boost campaign for this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boosted_reels', to='api.boostcampaign'),
        ),
        migrations.AddIndex(
            model_name='booststats',
            index=models.Index(fields=['campaign', '-date'], name='api_boostst_campaig_a52ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='booststats',
            index=models.Index(fields=['date'], name='api_boostst_date_3fb105_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booststats',
            unique_together={('campaign', 'date')},
        ),
        migrations.AddIndex(
            model_name='boostimpression',
            index=models.Index(fields=['campaign', 'viewer'], name='api_boostim_campaig_9f6f27_idx'),
        ),
        migrations.AddIndex(
            model_name='boostimpression',
            index=models.Index(fields=['viewer', 'viewed_at'], name='api_boostim_viewer__5d355a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boostimpression',
            unique_together={('campaign', 'viewer')},
        ),
        migrations.AddIndex(
            model_name='boostengagement',
            index=models.Index(fields=['campaign', 'engagement_type'], name='api_boosten_campaig_97caff_idx'),
        ),
        migrations.AddIndex(
            model_name='boostengagement',
            index=models.Index(fields=['user', '-created_at'], name='api_boosten_user_id_3ec05b_idx'),
        ),
        migrations.AddIndex(
            model_name='boostcampaign',
            index=models.Index(fields=['user', '-created_at'], name='api_boostca_user_id_d65769_idx'),
        ),
        migrations.AddIndex(
            model_name='boostcampaign',
            index=models.Index(fields=['reel', '-created_at'], name='api_boostca_reel_id_0d8b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='boostcampaign',
            index=models.Index(fields=['status', '-created_at'], name='api_boostca_status_ef2342_idx'),
        ),
        migrations.AddIndex(
            model_name='boostcampaign',
            index=models.Index(fields=['end_time'], name='api_boostca_end_tim_f83293_idx'),
        ),
    ]
