# Generated by Django 4.2.7 on 2026-05-21 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0086_add_moderation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationaction',
            name='undone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='undone_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='undone_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_undone', to=settings.AUTH_USER_MODEL),
        ),
    ]
