# Generated by Django 4.2.7 on 2026-05-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_moderationaction_undone_moderationaction_undone_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANT', 'Grant'), ('REVOKE', 'Revoke')], max_length=10)),
                ('target_user', models.CharField(max_length=150)),
                ('target_user_id', models.IntegerField()),
                ('performed_by', models.CharField(max_length=150)),
                ('performed_by_id', models.IntegerField()),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Privilege Audit Log',
                'verbose_name_plural': 'Privilege Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
