# Generated by Django 4.2.7 on 2026-05-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_privilegeauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='permission_level',
            field=models.CharField(choices=[('read_only', 'Read Only'), ('edit_only', 'Edit Only'), ('full', 'Full Access')], default='read_only', help_text='Granular permission level for this role', max_length=20),
        ),
    ]
