# Generated by Django 4.2.7 on 2026-05-26 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0089_adminrole_permission_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('UNAUTHORIZED_API', 'Unauthorized API Access'), ('UNAUTHORIZED_PAGE', 'Unauthorized Page Access'), ('PERMISSION_DENIED', 'Permission Denied'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('BRUTE_FORCE_ATTEMPT', 'Brute Force Attempt'), ('ADMIN_ACTION', 'Admin Action')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('page', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_securit_timesta_771a84_idx'), models.Index(fields=['event_type'], name='api_securit_event_t_8854c5_idx'), models.Index(fields=['severity'], name='api_securit_severit_5d7aa3_idx'), models.Index(fields=['is_resolved'], name='api_securit_is_reso_d46444_idx')],
            },
        ),
    ]
