# Generated by Django 4.2.7 on 2026-05-29 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0091_securityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=20)),
                ('granted', models.BooleanField()),
                ('source', models.CharField(default='in_app', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('disclosure_version', models.CharField(default='2026.05', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent History',
                'verbose_name_plural': 'Consent History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('camera', 'Camera Access'), ('storage', 'Storage Access'), ('analytics', 'Analytics'), ('marketing', 'Marketing'), ('gdpr_banner', 'Cookie and Tracking Banner'), ('privacy_policy', 'Privacy Policy Acceptance')], max_length=50)),
                ('granted', models.BooleanField(default=False)),
                ('source', models.CharField(default='in_app', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('disclosure_version', models.CharField(default='2026.05', max_length=20)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'consent_type')},
            },
        ),
    ]
