# Generated by Django 4.2.7 on 2026-05-29 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0092_consenthistory_userconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='drafts/')),
                ('media', models.FileField(blank=True, null=True, upload_to='drafts/')),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('overlay_text', models.TextField(blank=True, default='')),
                ('filter', models.CharField(blank=True, default='none', max_length=50)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='drafts/audio/')),
                ('audio_volume_level', models.IntegerField(default=80)),
                ('original_volume_level', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
