# Generated by Django 4.2.7 on 2026-06-02 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0094_subscription_grace_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMGiftAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('award', 'Award Package'), ('retry', 'Retry Failed'), ('cancel', 'Cancel'), ('manual', 'Manual Override')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMGiftPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Package name (e.g., '1GB Data Package')", max_length=200)),
                ('offering_id', models.CharField(help_text='CRM OfferingId from Ethio Telecom', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Package description')),
                ('charge_amount', models.DecimalField(decimal_places=2, help_text='Amount in ETB to charge for this package', max_digits=10)),
                ('min_level', models.IntegerField(default=1, help_text='Minimum user level required')),
                ('min_coins', models.IntegerField(default=0, help_text='Minimum coins required to claim')),
                ('trigger_condition', models.CharField(choices=[('campaign_win', 'Campaign Win'), ('contest_win', 'Contest Win'), ('leaderboard_top', 'Leaderboard Top Position'), ('manual', 'Manual Award')], default='manual', help_text='When this package is awarded', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this package is available')),
                ('max_awards_per_user', models.IntegerField(default=1, help_text='Maximum times a user can receive this package (0 = unlimited)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CRMGiftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number sent to CRM', max_length=20)),
                ('offering_id', models.CharField(help_text='CRM OfferingId used', max_length=50)),
                ('transaction_id', models.CharField(help_text='CRM TransactionId', max_length=50, unique=True)),
                ('charge_amount', models.DecimalField(decimal_places=2, help_text='Amount charged in ETB', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('response_message', models.TextField(blank=True, help_text='CRM response message')),
                ('response_code', models.CharField(blank=True, help_text='CRM RetCode', max_length=10)),
                ('trigger_source', models.CharField(blank=True, help_text="What triggered this gift (e.g., 'campaign_123', 'manual_admin')", max_length=50)),
                ('campaign_id', models.IntegerField(blank=True, help_text='Related campaign ID if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When CRM request completed', null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.crmgiftpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crmgiftpackage',
            index=models.Index(fields=['offering_id'], name='api_crmgift_offerin_b5a0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgiftpackage',
            index=models.Index(fields=['is_active'], name='api_crmgift_is_acti_4d66f6_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgiftpackage',
            index=models.Index(fields=['trigger_condition'], name='api_crmgift_trigger_6369ac_idx'),
        ),
        migrations.AddField(
            model_name='crmgiftauditlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crmgiftauditlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.crmgifttransaction'),
        ),
        migrations.AddIndex(
            model_name='crmgifttransaction',
            index=models.Index(fields=['user', '-created_at'], name='api_crmgift_user_id_5d67cb_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgifttransaction',
            index=models.Index(fields=['transaction_id'], name='api_crmgift_transac_af2995_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgifttransaction',
            index=models.Index(fields=['status'], name='api_crmgift_status_dea0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgifttransaction',
            index=models.Index(fields=['phone_number'], name='api_crmgift_phone_n_b16637_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgifttransaction',
            index=models.Index(fields=['offering_id'], name='api_crmgift_offerin_e5d718_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgiftauditlog',
            index=models.Index(fields=['transaction', '-created_at'], name='api_crmgift_transac_35066e_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgiftauditlog',
            index=models.Index(fields=['action'], name='api_crmgift_action_3c2fb7_idx'),
        ),
    ]
