# Generated by Django 4.2.7 on 2026-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_crm_gift_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='setup_otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='OTP expiration timestamp for subscription flow', null=True),
        ),
    ]
