# Generated by Django 4.2.7 on 2026-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_add_setup_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, help_text='Account locked until this time due to too many failed attempts', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, help_text='Number of consecutive failed login attempts'),
        ),
    ]
