# Generated by Django 4.2.7 on 2026-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_remove_miniapp_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='mandate_contract_id',
            field=models.CharField(blank=True, help_text='Telebirr mandate contract ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='mandate_status',
            field=models.CharField(blank=True, help_text='Mandate contract status from Telebirr', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='mct_contract_no',
            field=models.CharField(blank=True, help_text='Merchant contract number for mandate', max_length=32, null=True),
        ),
    ]
