# Generated by Django 4.2.7 on 2026-06-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_subscriptionplan_mandate_contract_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='telebirr_phone_number',
            field=models.CharField(blank=True, help_text='Phone number from Telebirr SuperApp', max_length=20, null=True),
        ),
    ]
