# Generated by Django 4.2.7 on 2026-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_subscriptionplan_telebirr_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_token',
            field=models.CharField(blank=True, help_text='Secure token for subscription flow URL', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Token expiration timestamp', null=True),
        ),
    ]
