# Generated by Django 4.2.7 on 2026-06-20 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0102_subscriptionplan_subscription_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTelebirrMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mct_contract_no', models.CharField(db_index=True, help_text='Merchant contract number sent in mandate_data', max_length=32, unique=True)),
                ('plan_type', models.CharField(blank=True, help_text='daily/weekly/monthly', max_length=20, null=True)),
                ('prepay_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merch_order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('mandate_template_id', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Payer phone, if known at preorder time', max_length=20, null=True)),
                ('mandate_contract_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pending Telebirr Mandate',
                'verbose_name_plural': 'Pending Telebirr Mandates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='api_pending_status_8d1fae_idx')],
            },
        ),
        migrations.CreateModel(
            name='B2CPaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver_msisdn', models.CharField(help_text='Customer phone number (MSISDN)', max_length=20)),
                ('receiver_account_name', models.CharField(blank=True, help_text='Receiver account name', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='ETB', help_text='Currency code (ISO 4217)', max_length=3)),
                ('reason_type', models.CharField(help_text='Reason type for the payment', max_length=100)),
                ('remark', models.TextField(blank=True, help_text='Additional remarks')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('telebirr_transaction_id', models.CharField(blank=True, help_text='Telebirr transaction ID', max_length=100)),
                ('originator_conversation_id', models.CharField(blank=True, help_text='Originator conversation ID', max_length=100)),
                ('conversation_id', models.CharField(blank=True, help_text='Telebirr conversation ID', max_length=100)),
                ('reference_data', models.JSONField(blank=True, default=dict, help_text='Additional reference data')),
                ('error_message', models.TextField(blank=True, help_text='Error message if payment failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payer', models.ForeignKey(help_text='User/organization initiating the payment', on_delete=django.db.models.deletion.CASCADE, related_name='b2c_payments_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'B2C Payment Transaction',
                'verbose_name_plural': 'B2C Payment Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payer', '-created_at'], name='api_b2cpaym_payer_i_898e62_idx'), models.Index(fields=['receiver_msisdn', '-created_at'], name='api_b2cpaym_receive_4149a8_idx'), models.Index(fields=['status', '-created_at'], name='api_b2cpaym_status_25e40f_idx'), models.Index(fields=['telebirr_transaction_id'], name='api_b2cpaym_telebir_a7db12_idx')],
            },
        ),
    ]
