# Generated by Django 4.2.7 on 2026-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_pendingtelebirrmandate_b2cpaymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinbalance',
            name='airtime_purchased_balance',
            field=models.PositiveIntegerField(default=0, help_text='Bought via Airtime. Cannot be gifted.'),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='telebirr_purchased_balance',
            field=models.PositiveIntegerField(default=0, help_text='Bought via Telebirr. Full use including gifting.'),
        ),
        migrations.AlterField(
            model_name='usercoinbalance',
            name='purchased_balance',
            field=models.PositiveIntegerField(default=0, help_text='Total purchased coins (Telebirr + Airtime).'),
        ),
    ]
