# Generated by Django 5.0.6 on 2026-07-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_directdebitmandate_user'),
        ('api', '0104_usercoinbalance_airtime_purchased_balance_and_more'),
    ]

    operations = [
    ]
