# Generated by Django 5.0.6 on 2026-07-09 08:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_merge_20260709_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='mandate_name',
            field=models.CharField(blank=True, help_text='Telebirr mandate name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='mandate_template_id',
            field=models.CharField(blank=True, help_text='Telebirr mandate template ID', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='merchant_code',
            field=models.CharField(blank=True, help_text='Telebirr merchant code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='merchant_name',
            field=models.CharField(blank=True, help_text='Telebirr merchant name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='single_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Single transaction amount for mandate', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\hp\\Downloads\\flip-master (4)\\flip-master\\backend\\media'), upload_to='messages/%Y/%m/'),
        ),
    ]
