# Generated by Django 4.2.7 on 2026-07-14 12:34

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0106_subscriptiontier_mandate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\hp\\Downloads\\Telegram Desktop\\postwork\\flipstar\\backend\\media'), upload_to='messages/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='PaymentTransactionBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_system', models.CharField(choices=[('telebirr_direct_debit', 'Telebirr Direct Debit'), ('onevas', 'Onevas'), ('telebirr_superapp', 'Telebirr SuperApp')], db_index=True, max_length=30)),
                ('source_model', models.CharField(choices=[('DirectDebitTransaction', 'Direct Debit Transaction'), ('OnevasChargingTransaction', 'Onevas Charging Transaction'), ('SubscriptionPayment', 'Subscription Payment')], db_index=True, max_length=50)),
                ('source_id', models.UUIDField(db_index=True, help_text='Original record ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('mandate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mandate_contract_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mct_contract_no', models.CharField(blank=True, max_length=32, null=True)),
                ('subscription_id', models.UUIDField(blank=True, null=True)),
                ('subscription_payment_id', models.UUIDField(blank=True, null=True)),
                ('telebirr_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('onevas_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_number', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('full_snapshot', models.JSONField(blank=True, default=dict, help_text='Complete original record data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this backup record should be deleted')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction Backup',
                'verbose_name_plural': 'Payment Transaction Backups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_system', '-created_at'], name='api_payment_payment_b41d02_idx'), models.Index(fields=['source_model', 'source_id'], name='api_payment_source__65f829_idx'), models.Index(fields=['expires_at'], name='api_payment_expires_2eaa86_idx'), models.Index(fields=['status', '-created_at'], name='api_payment_status_5aeaec_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMandateBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_system', models.CharField(choices=[('telebirr_superapp', 'Telebirr SuperApp'), ('telebirr_direct_debit', 'Telebirr Direct Debit'), ('onevas', 'Onevas')], db_index=True, max_length=30)),
                ('source_model', models.CharField(choices=[('PendingTelebirrMandate', 'Pending Telebirr Mandate'), ('SubscriptionPlan', 'Subscription Plan'), ('DirectDebitMandate', 'Direct Debit Mandate'), ('OnevasChargingTransaction', 'Onevas Charging Transaction')], db_index=True, max_length=50)),
                ('source_id', models.UUIDField(db_index=True, help_text='Original record ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mandate_contract_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mct_contract_no', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('mandate_id', models.CharField(blank=True, db_index=True, max_length=18, null=True)),
                ('payer_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('onevas_subscription_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('onevas_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('onevas_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_type', models.CharField(blank=True, help_text='daily/weekly/monthly', max_length=20, null=True)),
                ('tier_id', models.UUIDField(blank=True, null=True)),
                ('subscription_plan_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('mandate_template_id', models.CharField(blank=True, max_length=20, null=True)),
                ('mandate_status', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('frequency', models.CharField(blank=True, max_length=2, null=True)),
                ('prepay_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merch_order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_number', models.CharField(blank=True, max_length=50, null=True)),
                ('application_key', models.CharField(blank=True, max_length=100, null=True)),
                ('original_status', models.CharField(blank=True, max_length=50, null=True)),
                ('full_snapshot', models.JSONField(blank=True, default=dict, help_text='Complete original record data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this backup record should be deleted')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_mandate_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Mandate Backup',
                'verbose_name_plural': 'Payment Mandate Backups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_system', '-created_at'], name='api_payment_payment_719b6e_idx'), models.Index(fields=['source_model', 'source_id'], name='api_payment_source__5346db_idx'), models.Index(fields=['expires_at'], name='api_payment_expires_479cca_idx')],
            },
        ),
    ]
