# Generated by Django 4.2.7 on 2026-07-20 13:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_payment_backup_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebitmandate',
            name='debit_conversation_id',
            field=models.CharField(blank=True, help_text='Debit initiation conversation ID for transaction result matching', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='https://uat.flipstar.et/flipstar-media/', location='C:\\Users\\hp\\Downloads\\Telegram Desktop\\postwork\\flipstar\\backend\\media'), upload_to='messages/%Y/%m/'),
        ),
    ]
