# Generated by Django 5.0.6 on 2026-07-24 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_add_debit_conversation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerGiftPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_type', models.CharField(choices=[('daily', 'Daily Winner'), ('weekly', 'Weekly Winner'), ('monthly', 'Monthly Winner'), ('grand', 'Grand Winner')], max_length=20, unique=True)),
                ('gift_type', models.CharField(choices=[('data', 'Data Gift (MB)'), ('cash', 'Cash Gift (ETB)')], max_length=20)),
                ('payment_method', models.CharField(choices=[('crm', 'CRM (Data Gift)'), ('telebirr_b2c', 'Telebirr B2C (Cash Gift)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in ETB or MB', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Winner Gift Package',
                'verbose_name_plural': 'Winner Gift Packages',
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='payment_order_id',
            field=models.CharField(blank=True, help_text='Telebirr payment order ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment reference (e.g., merch_order_id for one-time Telebirr)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='total_airtime_purchased',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime coins bought via Airtime'),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='total_telebirr_purchased',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime coins bought via Telebirr'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='b2c_transaction_id',
            field=models.UUIDField(blank=True, help_text='Linked B2CPaymentTransaction ID', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='conversation_id',
            field=models.CharField(blank=True, help_text='B2C conversation ID from Telebirr', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='originator_conversation_id',
            field=models.CharField(blank=True, help_text='B2C originator conversation ID', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='platform_fee_birr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee (20% of gross)', max_digits=12),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='telebirr_transaction_id',
            field=models.CharField(blank=True, help_text='Telebirr transaction ID', max_length=100),
        ),
        migrations.CreateModel(
            name='WinnerGiftTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('winner_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('receiver_msisdn', models.CharField(blank=True, max_length=20)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100)),
                ('conversation_id', models.CharField(blank=True, max_length=100)),
                ('telebirr_transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped (Not Telebirr User)')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.winnergiftpackage')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Winner Gift Transaction',
                'verbose_name_plural': 'Winner Gift Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['winner', '-created_at'], name='api_winnerg_winner__f4bbb6_idx'), models.Index(fields=['winner_type', '-created_at'], name='api_winnerg_winner__96c716_idx'), models.Index(fields=['status'], name='api_winnerg_status_275e8c_idx'), models.Index(fields=['originator_conversation_id'], name='api_winnerg_origina_0b44cd_idx')],
            },
        ),
    ]
