# Generated by Django 5.0.6 on 2026-07-27 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_winnergiftpackage_subscriptionplan_payment_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_win_limit_per_month',
            field=models.IntegerField(default=1, help_text='Max daily wins per month per user'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_win_limit_per_campaign',
            field=models.IntegerField(default=1, help_text='Max grand wins per campaign per user'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_win_limit_per_period',
            field=models.IntegerField(default=1, help_text='Max monthly wins per campaign period per user'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_win_limit_per_month',
            field=models.IntegerField(default=1, help_text='Max weekly wins per month per user'),
        ),
        migrations.CreateModel(
            name='WinnerFrequencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('grand', 'Grand')], max_length=20)),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField(help_text='Start of the period this win belongs to')),
                ('period_end', models.DateTimeField(help_text='End of the period this win belongs to')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_frequency_records', to='api.campaign')),
                ('selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frequency_records', to='api.winnerselection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_frequency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-won_at'],
                'indexes': [models.Index(fields=['user', 'winner_type', '-won_at'], name='api_winnerf_user_id_531275_idx'), models.Index(fields=['winner_type', 'period_start', 'period_end'], name='api_winnerf_winner__0fddd1_idx')],
                'unique_together': {('user', 'winner_type', 'period_start')},
            },
        ),
    ]
