# Generated by Django 5.0.6 on 2026-07-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_campaignscoringconfig_daily_win_limit_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_received_welcome_bonus',
            field=models.BooleanField(default=False, help_text='User has received one-time welcome bonus (3 coins)'),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_comment_non_campaign',
            field=models.PositiveIntegerField(default=1, help_text='Coins charged when commenting on a non-campaign post'),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_share_non_campaign',
            field=models.PositiveIntegerField(default=1, help_text='Coins charged when sharing a non-campaign post'),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='welcome_bonus',
            field=models.PositiveIntegerField(default=3, help_text='Coins given to new users on signup (one-time per phone number)'),
        ),
    ]
