# Generated by Django 5.0.6 on 2026-07-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_userprofile_has_received_welcome_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_comment',
            field=models.PositiveIntegerField(default=1, help_text='Coins charged when commenting on a campaign post'),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_share',
            field=models.PositiveIntegerField(default=1, help_text='Coins charged when sharing a campaign post'),
        ),
    ]
