# Generated by Django 5.0.6 on 2026-07-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_alter_walletconfig_cost_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_comment',
            field=models.PositiveIntegerField(default=0, help_text='Coins charged when commenting on a campaign post (0 = free)'),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_comment_non_campaign',
            field=models.PositiveIntegerField(default=0, help_text='Coins charged when commenting on a non-campaign post (0 = free)'),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_share',
            field=models.PositiveIntegerField(default=0, help_text='Coins charged when sharing a campaign post (0 = free)'),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_share_non_campaign',
            field=models.PositiveIntegerField(default=0, help_text='Coins charged when sharing a non-campaign post (0 = free)'),
        ),
    ]
