# Generated by Django 5.0.6 on 2026-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_alter_walletconfig_cost_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpackage',
            name='allows_airtime',
            field=models.BooleanField(default=False),
        ),
    ]
