from django.core.management.base import BaseCommand
from api.models_subscription import SubscriptionTier
from django.utils import timezone


class Command(BaseCommand):
    help = 'Seed subscription tiers with Onevas configuration'

    def handle(self, *args, **options):
        tiers_data = [
            {
                'name': 'Daily Premium',
                'slug': 'daily',
                'description': '24-hour access to premium features',
                'duration_type': 'daily',
                'duration_days': 1,
                'price_etb': 3.00,
                'price_coins': None,
                'onevas_code': 'A',
                'spid': '300263',
                'service_id': '30026300007331',
                'product_id': '10000302850',
                'application_key': 'UPJG5ZM3X6C9LLDSKKCME4MA86UQRKWV',
                'short_code': '9286',
                'features': ['View all content', 'Basic interactions'],
                'privileges': {
                    'max_posts_per_day': 10,
                    'max_reels_per_day': 5,
                    'max_campaigns_per_month': 0,
                    'max_likes_per_day': 100,
                    'max_comments_per_day': 50,
                    'max_follows_per_day': 20,
                    'priority_support': False,
                    'custom_themes': False,
                    'analytics_access': False,
                    'api_access': False,
                    'ad_free': False,
                    'watermark_free': False,
                    'hd_quality': False,
                    'download_videos': False,
                    'profile_badge': 'Daily Premium'
                },
                'max_posts_per_day': 10,
                'max_reels_per_day': 5,
                'max_campaigns_per_month': 0,
                'max_likes_per_day': 100,
                'max_comments_per_day': 50,
                'max_follows_per_day': 20,
                'priority_support': False,
                'custom_themes': False,
                'analytics_access': False,
                'api_access': False,
                'ad_free': False,
                'watermark_free': False,
                'hd_quality': False,
                'download_videos': False,
                'is_active': True,
                'sort_order': 1,
            },
            {
                'name': 'Weekly Premium',
                'slug': 'weekly',
                'description': '7-day access to premium features',
                'duration_type': 'weekly',
                'duration_days': 7,
                'price_etb': 20.00,
                'price_coins': None,
                'onevas_code': 'B',
                'spid': '300263',
                'service_id': '30026300007332',
                'product_id': '10000302851',
                'application_key': 'I6QEX9W5D341NN50QPB0KQ9HW6DH99TQ',
                'short_code': '9286',
                'features': ['View all content', 'Extended interactions', 'HD quality'],
                'privileges': {
                    'max_posts_per_day': 15,
                    'max_reels_per_day': 8,
                    'max_campaigns_per_month': 1,
                    'max_likes_per_day': 200,
                    'max_comments_per_day': 100,
                    'max_follows_per_day': 50,
                    'priority_support': False,
                    'custom_themes': False,
                    'analytics_access': False,
                    'api_access': False,
                    'ad_free': False,
                    'watermark_free': False,
                    'hd_quality': True,
                    'download_videos': False,
                    'profile_badge': 'Weekly Premium'
                },
                'max_posts_per_day': 15,
                'max_reels_per_day': 8,
                'max_campaigns_per_month': 1,
                'max_likes_per_day': 200,
                'max_comments_per_day': 100,
                'max_follows_per_day': 50,
                'priority_support': False,
                'custom_themes': False,
                'analytics_access': False,
                'api_access': False,
                'ad_free': False,
                'watermark_free': False,
                'hd_quality': True,
                'download_videos': False,
                'is_active': True,
                'sort_order': 2,
            },
            {
                'name': 'Monthly Premium',
                'slug': 'monthly',
                'description': '30-day access to all premium features',
                'duration_type': 'monthly',
                'duration_days': 30,
                'price_etb': 70.00,
                'price_coins': None,
                'onevas_code': 'C',
                'spid': '300263',
                'service_id': '30026300007333',
                'product_id': '10000302852',
                'application_key': '0Y72TFLJP4ZAQ127K0O43IJSD9QAPTWQ',
                'short_code': '9286',
                'features': ['All features', 'Priority support', 'Custom themes', 'Analytics', 'Ad-free', 'Download videos'],
                'privileges': {
                    'max_posts_per_day': 30,
                    'max_reels_per_day': 15,
                    'max_campaigns_per_month': 5,
                    'max_likes_per_day': 500,
                    'max_comments_per_day': 250,
                    'max_follows_per_day': 100,
                    'priority_support': True,
                    'custom_themes': True,
                    'analytics_access': True,
                    'api_access': False,
                    'ad_free': True,
                    'watermark_free': True,
                    'hd_quality': True,
                    'download_videos': True,
                    'profile_badge': 'Monthly Premium'
                },
                'max_posts_per_day': 30,
                'max_reels_per_day': 15,
                'max_campaigns_per_month': 5,
                'max_likes_per_day': 500,
                'max_comments_per_day': 250,
                'max_follows_per_day': 100,
                'priority_support': True,
                'custom_themes': True,
                'analytics_access': True,
                'api_access': False,
                'ad_free': True,
                'watermark_free': True,
                'hd_quality': True,
                'download_videos': True,
                'is_active': True,
                'sort_order': 3,
            },
            {
                'name': 'OnDemand Premium',
                'slug': 'ondemand',
                'description': 'One-time purchase with 100 coins',
                'duration_type': 'ondemand',
                'duration_days': None,
                'price_etb': 10.00,
                'price_coins': 100,
                'onevas_code': 'D',
                'spid': '300263',
                'service_id': '30026300007334',
                'product_id': '10000302853',
                'application_key': '4CROFBT0EGCM1OK8R88EQBTEZOMI3138',
                'short_code': '9286',
                'features': ['All features', 'API access', 'Lifetime access'],
                'privileges': {
                    'max_posts_per_day': 50,
                    'max_reels_per_day': 25,
                    'max_campaigns_per_month': 10,
                    'max_likes_per_day': 1000,
                    'max_comments_per_day': 500,
                    'max_follows_per_day': 200,
                    'priority_support': True,
                    'custom_themes': True,
                    'analytics_access': True,
                    'api_access': True,
                    'ad_free': True,
                    'watermark_free': True,
                    'hd_quality': True,
                    'download_videos': True,
                    'profile_badge': 'OnDemand Premium'
                },
                'max_posts_per_day': 50,
                'max_reels_per_day': 25,
                'max_campaigns_per_month': 10,
                'max_likes_per_day': 1000,
                'max_comments_per_day': 500,
                'max_follows_per_day': 200,
                'priority_support': True,
                'custom_themes': True,
                'analytics_access': True,
                'api_access': True,
                'ad_free': True,
                'watermark_free': True,
                'hd_quality': True,
                'download_videos': True,
                'is_active': True,
                'sort_order': 4,
            },
        ]

        for tier_data in tiers_data:
            tier, created = SubscriptionTier.objects.get_or_create(
                slug=tier_data['slug'],
                defaults=tier_data
            )
            
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created tier: {tier.name}'))
            else:
                # Update existing tier
                for key, value in tier_data.items():
                    setattr(tier, key, value)
                tier.save()
                self.stdout.write(self.style.WARNING(f'Updated tier: {tier.name}'))

        self.stdout.write(self.style.SUCCESS('Subscription tiers seeded successfully'))
