const PATTERNS = [
  "^/admin/contest/judge/\\d+/$",
  "^/admin/master\\-campaigns/\\d+/participants/$",
  "^/auth/change\\-password/$",
  "^/auth/check\\-phone\\-account/$",
  "^/auth/delete\\-account/$",
  "^/auth/dev\\-create\\-subscription/$",
  "^/auth/download\\-data/$",
  "^/auth/forgot\\-password\\-phone/$",
  "^/auth/forgot\\-password\\-phone/verify/$",
  "^/auth/forgot\\-password/$",
  "^/auth/forgot\\-password/confirm/$",
  "^/auth/login\\-with\\-phone/$",
  "^/auth/login\\-with\\-subscription\\-otp/$",
  "^/auth/login/$",
  "^/auth/register\\-with\\-phone/$",
  "^/auth/register/$",
  "^/auth/reset\\-password/$",
  "^/auth/send\\-phone\\-otp/$",
  "^/auth/verify\\-phone\\-otp/$",
  "^/blocks/$",
  "^/blocks/.*",
  "^/follows/$",
  "^/follows/.*",
  "^/gifts/$",
  "^/gifts/.*",
  "^/boost/calculate\\-cost/$",
  "^/boost/campaigns/$",
  "^/boost/campaigns/\\d+/$",
  "^/boost/campaigns/\\d+/cancel/$",
  "^/boost/campaigns/\\d+/pause/$",
  "^/boost/campaigns/\\d+/resume/$",
  "^/boost/campaigns/my/$",
  "^/boost/config/$",
  "^/boost/eligible/$",
  "^/boost/engagement/$",
  "^/boost/impression/$",
  "^/boost/pacing\\-check/$",
  "^/campaigns/$",
  "^/campaigns/\\d+/$",
  "^/campaigns/\\d+/consistency/update/$",
  "^/campaigns/\\d+/engagement/update/$",
  "^/campaigns/\\d+/enter/$",
  "^/campaigns/\\d+/extended/$",
  "^/campaigns/\\d+/feed/$",
  "^/campaigns/\\d+/finalists/voting/$",
  "^/campaigns/\\d+/scoring\\-config/$",
  "^/campaigns/\\d+/vote/$",
  "^/campaigns/active/$",
  "^/campaigns/entries/\\d+/vote/$",
  "^/campaigns/notifications/$",
  "^/campaigns/profile/$",
  "^/campaigns/profile/\\d+/$",
  "^/categories/$",
  "^/charging/coin\\-purchase/$",
  "^/charging/on\\-demand/$",
  "^/charging/on\\-demand/analytics/$",
  "^/charging/on\\-demand/search/$",
  "^/charging/on\\-demand/statistics/$",
  "^/charging/on\\-demand/transactions/$",
  "^/charging/ussd\\-push/request\\-otp/$",
  "^/charging/ussd\\-push/verify\\-otp/$",
  "^/charging/ussd\\-push/.*$",
  "^/coins/balance/$",
  "^/coins/boost/$",
  "^/coins/extra\\-entry/$",
  "^/coins/gift/$",
  "^/coins/packages/$",
  "^/coins/purchase/$",
  "^/coins/send\\-gift/$",
  "^/coins/transactions/$",
  "^/direct\\-debit/activate/$",
  "^/direct\\-debit/cancel/$",
  "^/direct\\-debit/create/$",
  "^/direct\\-debit/initiate/$",
  "^/direct\\-debit/mandates/$",
  "^/direct\\-debit/one\\-off\\-coin\\-purchase/$",
  "^/eligibility/age/$",
  "^/eligibility/phone/$",
  "^/explorer/hashtag/$",
  "^/explorer/trending\\-hashtags/$",
  "^/explorer/trending/$",
  "^/gamification/activity/$",
  "^/gamification/checkin/$",
  "^/gamification/debug/$",
  "^/gamification/gift/$",
  "^/gamification/gifts/history/$",
  "^/gifts/send/$",
  "^/gamification/login\\-bonus/$",
  "^/gamification/status/$",
  "^/grand\\-finale/$",
  "^/grand\\-finale/vote/$",
  "^/leaderboard/$",
  "^/legal/$",
  "^/legal/[^/]+/$",
  "^/legal/[^/]+/accept/$",
  "^/legal/user/history/$",
  "^/legal/user/pending/$",
  "^/messages/\\d+/$",
  "^/messages/conversations/$",
  "^/messages/conversations/\\d+/read/$",
  "^/messages/unread\\-count/$",
  "^/messages/users/search/$",
  "^/notifications/$",
  "^/notifications/\\d+/read/$",
  "^/notifications/me/$",
  "^/notifications/me/update/$",
  "^/notifications/read/$",
  "^/notifications/unread\\-count/$",
  "^/profile/privacy/$",
  "^/profile/privacy/update/$",
  "^/push/public\\-key/$",
  "^/push/subscribe/$",
  "^/push/unsubscribe/$",
  "^/reels/\\d+/view/$",
  "^/reels/following/$",
  "^/reels/not\\-interested/$",
  "^/reels/not\\-interested/undo/$",
  "^/reels/saved/$",
  "^/reels/trending/$",
  "^/reports/create/$",
  "^/scores/\\d+/$",
  "^/search/$",
  "^/settings/public/$",
  "^/subscription/details/$",
  "^/subscription/status/$",
  "^/subscription/telebirr/ussd/initiate/$",
  "^/subscription/upgrade/$",
  "^/subscriptions/tiers/$",
  "^/subscriptions/tiers/active/$",
  "^/support/requests/$",
  "^/upload/check/$",
  "^/wallet/$",
  "^/wallet/config/$",
  "^/wallet/reinvest/$",
  "^/wallet/telebirr/initiate/$",
  "^/wallet/telebirrUssdPurchase/$",
  "^/wallet/transactions/$",
  "^/wallet/withdraw/$",
  "^/wallet/withdrawal\\-info/$",
  "^/wallet/withdrawals/$",
  "^/wallet/withdrawals/\\d+/cancel/$",
].map((source) => new RegExp(source));

export function isEncryptedRoute(endpoint) {
  if (process.env.EXPO_PUBLIC_USE_ENCRYPTION === 'false') return false;
  if (typeof endpoint !== 'string' || endpoint.length === 0) return false;

  let path = endpoint.split('?')[0].split('#')[0];
  if (path.startsWith('http://') || path.startsWith('https://')) {
    path = path.replace(/^https?:\/\/[^\/]+/, '');
  }

  if (path.startsWith('/api/v1/')) {
    path = path.replace('/api/v1', '');
  } else if (path.startsWith('/api/')) {
    path = path.replace('/api', '');
  } else if (path.startsWith('/v1/')) {
    path = path.replace('/v1', '');
  }

  const normalised = path.startsWith('/') ? path : `/${path}`;
  const withTrailingSlash = normalised.endsWith('/') ? normalised : `${normalised}/`;
  return PATTERNS.some((pattern) => pattern.test(withTrailingSlash));
}
