import { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation dictionary
const translations = {
  en: {
    settings: 'Settings',
    account: 'Account',
    notifications: 'Notifications',
    privacy: 'Privacy',
    appearance: 'Appearance',
    help: 'Help',
    darkMode: 'Dark Mode',
    language: 'Language',
    editProfile: 'Edit Profile',
    wallet: 'Wallet',
    subscription: 'Subscription',
    changePassword: 'Change PIN',
    downloadData: 'Download Data',
    likes: 'Likes',
    comments: 'Comments',
    follows: 'Follows',
    messages: 'Messages',
    privateAccount: 'Private Account',
    showActivity: 'Show Activity',
    allowMessages: 'Allow Messages',
    resetSuggestions: 'Reset Suggested Content',
    helpCenter: 'Help Center',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    blockedUsers: 'Blocked Users',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to log out of your account?',
    chooseLanguage: 'Choose Language',
    currentPassword: 'Current PIN',
    newPassword: 'New PIN (6 digits)',
    confirmNewPassword: 'Confirm New PIN',
    updatePassword: 'Update PIN',
    english: 'English',
    amharic: 'አማርኛ (Amharic)',
    spanish: 'Español',
    french: 'Français',
    arabic: 'العربية',
    // Common UI elements
    error: 'Error',
    success: 'Success',
    failed: 'Failed',
    myWallet: 'My Wallet',
    coins: 'Coins',
    streak: 'Streak',
    points: 'Points',
    level: 'Level',
    buyCoins: 'Buy Coins',
    withdraw: 'Withdraw',
    history: 'History',
    coinPackages: 'Coin Packages',
    noPackagesAvailable: 'No packages available',
    allTransactions: 'All Transactions',
    noTransactionsYet: 'No transactions yet',
    withdrawals: 'Withdrawals',
    noWithdrawalsYet: 'No withdrawals yet',
    withdrawCoins: 'Withdraw Coins',
    amount: 'Amount',
    payoutMethod: 'Payout Method',
    withdrawRequest: 'Withdrawal request',
    paymentInitiated: 'Payment Initiated',
    completePayment: 'Complete payment in telebirr app',
    selectPackage: 'Select a package',
    enterPhone: 'Enter phone number',
    home: 'Home',
    reels: 'Reels',
    create: 'Create',
    explore: 'Explore',
    notifications: 'Notifications',
    profile: 'Profile',
    search: 'Search',
    login: 'Login',
    register: 'Register',
    subscribe: 'Subscribe',
    cancel: 'Cancel',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading',
    noData: 'No data',
  },
  am: {
    settings: 'ቅንብሮች',
    account: 'መለያ',
    notifications: 'ማስታወቂያዎች',
    privacy: 'የግላዊነት',
    appearance: 'አልባም',
    help: 'እርዳታ',
    darkMode: 'ጨለማ ዘዴ',
    language: 'ቋንቋ',
    editProfile: 'መለያ ማረም',
    wallet: 'የገንዘብ ቦርሳ',
    subscription: 'የመዝገብ ክፍያ',
    changePassword: 'ፒን መቀየር',
    downloadData: 'ዳታ ማውጣት',
    likes: 'የሚወዱ',
    comments: 'አስተያየት',
    follows: 'እየከነበሩ',
    messages: 'መልእክቶች',
    privateAccount: 'የግላዊ መለያ',
    showActivity: 'እንቅናት አሳይ',
    allowMessages: 'መልእክቶች ፍቀድ',
    resetSuggestions: 'የተገለጉ አስታዋቾችን እንደገና ማስጀመር',
    helpCenter: 'የእርዳታ ማእከል',
    privacyPolicy: 'የግላዊነት ፖሊሲ',
    termsOfService: 'የአገልግሎት ውልደታ',
    blockedUsers: 'የተከሉት ተጠቃሚዎች',
    dangerZone: 'የአደጋ ሜዳ',
    deleteAccount: 'መለያ መሰረዝ',
    logout: 'መውጣት',
    logoutConfirm: 'እርግጠኛ ነዎት ከመለያዎ መውጣት ይፈልጋሉ?',
    chooseLanguage: 'ቋንቋ ይምረጡ',
    currentPassword: 'የአሁኑ ፒን',
    newPassword: 'አዲስ ፒን (6 አሃዞች)',
    confirmNewPassword: 'አዲስ ፒን ያረጋግጡ',
    updatePassword: 'ፒን ያሻሽሉ',
    english: 'English',
    amharic: 'አማርኛ',
    spanish: 'Español',
    french: 'Français',
    arabic: 'العربية',
    // Common UI elements
    error: 'ስህተት',
    success: 'እምነት',
    failed: 'አልተሳካም',
    wallet: 'የገንዘብ ቦርሳ',
    myWallet: 'የእኔ የገንዘብ ቦርሳ',
    coins: 'ገንዘቦች',
    streak: 'ተከታል',
    points: 'ነጥብ',
    level: 'ረጃ',
    buyCoins: 'ገንዘብ ይግዙ',
    withdraw: 'ወሰዱ',
    history: 'ታሪክ',
    coinPackages: 'የገንዘብ እቅዶች',
    noPackagesAvailable: 'ምንም እቅዶች የሉም',
    allTransactions: 'ሁሉም ግብይናቶች',
    noTransactionsYet: 'ግብይናቶች ገና የሉም',
    withdrawals: 'ወሰዶች',
    noWithdrawalsYet: 'ወሰዶች ገና የሉም',
    withdrawCoins: 'ገንዘብ ወሰድ',
    amount: 'መጠን',
    payoutMethod: 'የክፍያ ዘዴ',
    withdrawRequest: 'የመውሰድ ጥያቄ',
    buyCoins: 'ገንዘብ ይግዙ',
    paymentInitiated: 'ክፍያ ተምረ',
    completePayment: 'ክፍያዉን በቴለብር ትርፍ ይምረጡ',
    selectPackage: 'እቅድ ይምረጡ',
    enterPhone: 'ስልክ ቁጥር ያስገቡ',
    home: 'ቤት',
    reels: 'ሬልስ',
    create: 'ፍጥር',
    explore: 'መረሳ',
    notifications: 'ማስታወቂያዎች',
    profile: 'መገለጫ',
    search: 'ፈልግ',
    login: 'ግቡ',
    register: 'ይመዝገቡ',
    subscribe: 'ይመዝገቡ',
    cancel: 'ተሰርዙ',
    ok: 'እሺ',
    yes: 'አዎ',
    no: 'አይደለም',
    loading: 'በመጫኛ ላይ',
    noData: 'ዳታ የለም',
  },
  es: {
    settings: 'Configuración',
    account: 'Cuenta',
    notifications: 'Notificaciones',
    privacy: 'Privacidad',
    appearance: 'Apariencia',
    help: 'Ayuda',
    darkMode: 'Modo Oscuro',
    language: 'Idioma',
    editProfile: 'Editar Perfil',
    wallet: 'Billetera',
    subscription: 'Suscripción',
    changePassword: 'Cambiar PIN',
    downloadData: 'Descargar Datos',
    likes: 'Me Gusta',
    comments: 'Comentarios',
    follows: 'Seguidores',
    messages: 'Mensajes',
    privateAccount: 'Cuenta Privada',
    showActivity: 'Mostrar Actividad',
    allowMessages: 'Permitir Mensajes',
    resetSuggestions: 'Restablecer Sugerencias',
    helpCenter: 'Centro de Ayuda',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    blockedUsers: 'Usuarios Bloqueados',
    dangerZone: 'Zona de Peligro',
    deleteAccount: 'Eliminar Cuenta',
    logout: 'Cerrar Sesión',
    logoutConfirm: '¿Estás seguro de que quieres cerrar sesión en tu cuenta?',
    chooseLanguage: 'Elegir Idioma',
    currentPassword: 'PIN Actual',
    newPassword: 'Nuevo PIN (6 dígitos)',
    confirmNewPassword: 'Confirmar Nuevo PIN',
    updatePassword: 'Actualizar PIN',
    english: 'English',
    amharic: 'አማርኛ (Amharic)',
    spanish: 'Español',
    french: 'Français',
    arabic: 'العربية',
  },
  fr: {
    settings: 'Paramètres',
    account: 'Compte',
    notifications: 'Notifications',
    privacy: 'Confidentialité',
    appearance: 'Apparence',
    help: 'Aide',
    darkMode: 'Mode Sombre',
    language: 'Langue',
    editProfile: 'Modifier le Profil',
    wallet: 'Portefeuille',
    subscription: 'Abonnement',
    changePassword: 'Changer le PIN',
    downloadData: 'Télécharger les Données',
    likes: 'J\'aime',
    comments: 'Commentaires',
    follows: 'Abonnés',
    messages: 'Messages',
    privateAccount: 'Compte Privé',
    showActivity: 'Afficher l\'Activité',
    allowMessages: 'Autoriser les Messages',
    resetSuggestions: 'Réinitialiser les Suggestions',
    helpCenter: 'Centre d\'Aide',
    privacyPolicy: 'Politique de Confidentialité',
    termsOfService: 'Conditions d\'Utilisation',
    blockedUsers: 'Utilisateurs Bloqués',
    dangerZone: 'Zone de Danger',
    deleteAccount: 'Supprimer le Compte',
    logout: 'Déconnexion',
    logoutConfirm: 'Êtes-vous sûr de vouloir vous déconnecter de votre compte ?',
    chooseLanguage: 'Choisir la Langue',
    currentPassword: 'PIN Actuel',
    newPassword: 'Nouveau PIN (6 chiffres)',
    confirmNewPassword: 'Confirmer le Nouveau PIN',
    updatePassword: 'Mettre à Jour le PIN',
    english: 'English',
    amharic: 'አማርኛ (Amharic)',
    spanish: 'Español',
    french: 'Français',
    arabic: 'العربية',
  },
  ar: {
    settings: 'الإعدادات',
    account: 'الحساب',
    notifications: 'الإشعارات',
    privacy: 'الخصوصية',
    appearance: 'المظهر',
    help: 'المساعدة',
    darkMode: 'الوضع الليلي',
    language: 'اللغة',
    editProfile: 'تعديل الملف الشخصي',
    wallet: 'المحفظة',
    subscription: 'الاشتراك',
    changePassword: 'تغيير الرمز السري',
    downloadData: 'تنزيل البيانات',
    likes: 'الإعجابات',
    comments: 'التعليقات',
    follows: 'المتابعون',
    messages: 'الرسائل',
    privateAccount: 'حساب خاص',
    showActivity: 'إظهار النشاط',
    allowMessages: 'السماح بالرسائل',
    resetSuggestions: 'إعادة تعيين الاقتراحات',
    helpCenter: 'مركز المساعدة',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    blockedUsers: 'المستخدمون المحظورون',
    dangerZone: 'منطقة الخطر',
    deleteAccount: 'حذف الحساب',
    logout: 'تسجيل الخروج',
    logoutConfirm: 'هل أنت متأكد أنك تريد تسجيل الخروج من حسابك؟',
    chooseLanguage: 'اختر اللغة',
    currentPassword: 'الرمز السري الحالي',
    newPassword: 'رمز سري جديد (6 أرقام)',
    confirmNewPassword: 'تأكيد الرمز السري الجديد',
    updatePassword: 'تحديث الرمز السري',
    english: 'English',
    amharic: 'አማርኛ (Amharic)',
    spanish: 'Español',
    french: 'Français',
    arabic: 'العربية',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState('en');

  const setLanguage = async (lang) => {
    setLanguageState(lang);
    try {
      await AsyncStorage.setItem('language', lang);
    } catch (error) {
      console.error('Failed to save language setting:', error);
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  // Load language preference on mount
  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const saved = await AsyncStorage.getItem('language');
        if (saved) {
          setLanguageState(saved);
        }
      } catch (error) {
        console.error('Failed to load language setting:', error);
      }
    };
    loadLanguage();
  }, []);

  const value = {
    language,
    setLanguage,
    t,
    translations: translations[language] || translations.en
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
